# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About',       url: 'about.html'}
- {name: 'Work',        url: 'work.html'}
- {name: 'Blog',        url: 'blog.html'}
- {name: 'Photography', url: 'photography.html'}
- {name: 'Protected',   url: 'pswd.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://www.github.com/an15ms157'}
- {icon: 'facebook',   link: 'https://www.facebook.com/icchyamoy/'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/abhishek-nath-17b07b116/'}
- {icon: 'envelope',   link: 'mailto:aabhishek.naath@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
